# conda env create -f environment.yml
name: ckan
channels:
  - conda-forge
dependencies:
  - pip
  - python=3
  - shapely
  - pandas
  - geopandas
  - spatialpandas
  - bokeh
  - matplotlib
  - datashader
  - holoviews
  - geoviews
