site_name: B2Find
site_url: http://b2find.eudat.eu/
site_dir: site
nav:
    - Home: index.md 
    - Data Catalogue: datacatalogue.md
    - Communities: communities.md
    - For Providers: forproviders.md
    - For Users: forusers.md
    - About: about.md

markdown_extensions:
    - toc:
        permalink: True

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - xml
        - python

